version: '3.9'

services:
  node:
    container_name: node_dev
    build:
      context: .
      dockerfile: ./.Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/src
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    container_name: every-realm-db
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=everyrealm
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres:
    driver: local
